import Images from '../ImagesPropertySlider';

const PropertyData = [
    {
      propertyDetails: '1 BHK FLAT All AMENITIES PROJECT FOR RENT IN BANER PUNE MAHARASHTRA',
      images: Images,
      propertyKey : 1201,
      propertyType: 'Residential',
      societyName: 'Sankalp',
      price: 10000,
      area: 350,
      amenities: 'abc, aaa, bbbb, cccc',
      type: 'Abcdef',
    },
    {
        propertyDetails: '1 BHK FLAT All AMENITIES PROJECT FOR RENT IN BANER PUNE MAHARASHTRA',
        images: Images,
        propertyKey : 1229,
        propertyType: 'Residential',
        societyName: 'Sankalp',
        price: 10000,
        area: 350,
        amenities: 'abc, aaa, bbbb, cccc',
        type: 'Abcdef',
      },
      {
        propertyDetails: '1 BHK FLAT All AMENITIES PROJECT FOR RENT IN BANER PUNE MAHARASHTRA',
        images: Images,
        propertyKey : 1228,
        propertyType: 'Residential',
        societyName: 'Sankalp',
        price: 10000,
        area: 350,
        amenities: 'abc, aaa, bbbb, cccc',
        type: 'Abcdef',
      },
      {
        propertyDetails: '1 BHK FLAT All AMENITIES PROJECT FOR RENT IN BANER PUNE MAHARASHTRA',
        images: Images,
        propertyKey : 1227,
        propertyType: 'Residential',
        societyName: 'Sankalp',
        price: 10000,
        area: 350,
        amenities: 'abc, aaa, bbbb, cccc',
        type: 'Abcdef',
      },
      {
        propertyDetails: '1 BHK FLAT All AMENITIES PROJECT FOR RENT IN BANER PUNE MAHARASHTRA',
        images: Images,
        propertyKey : 1226,
        propertyType: 'Residential',
        societyName: 'Sankalp',
        price: 10000,
        area: 350,
        amenities: 'abc, aaa, bbbb, cccc',
        type: 'Abcdef',
      },
      {
        propertyDetails: '1 BHK FLAT All AMENITIES PROJECT FOR RENT IN BANER PUNE MAHARASHTRA',
        images: Images,
        propertyKey : 1225,
        propertyType: 'Residential',
        societyName: 'Sankalp',
        price: 10000,
        area: 350,
        amenities: 'abc, aaa, bbbb, cccc',
        type: 'Abcdef',
      },
      {
        propertyDetails: '1 BHK FLAT All AMENITIES PROJECT FOR RENT IN BANER PUNE MAHARASHTRA',
        images: Images,
        propertyKey : 1224,
        propertyType: 'Residential',
        societyName: 'Sankalp',
        price: 10000,
        area: 350,
        amenities: 'abc, aaa, bbbb, cccc',
        type: 'Abcdef',
      },
    // Add more property objects here
  ];

  export default PropertyData